--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Sergittos/BedWars
build-by-default: true
branches:
- master
projects:
  BedWars:
    path: ""
    icon: icon.png
    libs:
      - src: dresnite/easyui/libEasyUI
        version: 1.0.3
        branch: pm5
...
